trigger:
- master

variables:
  azureSubscription: 'AzureServiceConnection'
  acrName: 'acrdevopsdemo01'
  aksCluster: 'aks-prod-demo'
  aksResourceGroup: 'rg-maingroup'
  imageName: 'karthickapp'
  buildId: '$(Build.BuildId)'
  imageTag: '$(acrName).azurecr.io/$(imageName):$(buildId)'

stages:

# -----------------------
# Build + Push Docker Image
# -----------------------
- stage: Build
  displayName: "Build and Push Docker Image"

  jobs:
  - job: BuildAndPush
    displayName: "Build and Push to ACR"

    pool:
      name: "Default"
      demands:
        - agent.name -equals Terraform

    steps:
    # Reset Git credentials
    - script: |
        git config --global --unset-all http.extraheader || true
        git config --local --unset-all http.extraheader || true
      displayName: "Reset leftover Git extraheader"

    - checkout: self
      clean: true
      persistCredentials: true

    - task: AzureCLI@2
      displayName: "Login to ACR and Build+Push Docker Image"
      inputs:
        azureSubscription: "$(azureSubscription)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging in to ACR..."
          az acr login --name $(acrName)

          echo "Building Docker image..."
          docker build --no-cache -t $(imageTag) .

          echo "Pushing Docker image..."
          docker push $(imageTag)

    # ---------- Trivy Image Scan ----------
    - task: Bash@3
      displayName: "Trivy Image Scan (HIGH/CRITICAL)"
      inputs:
        targetType: 'inline'
        script: |
          set -e

          echo "Installing Trivy locally (no sudo needed)..."
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./trivy-bin

          export PATH="$PWD/trivy-bin:$PATH"

          echo "Running Trivy scan on image $(imageTag)..."
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --ignore-unfixed \
            "$(imageTag)"

    # ---------- Trivy Configuration Scan (Helm + K8s YAML) ----------
    - task: Bash@3
      displayName: "Trivy Config Scan (Helm/Kubernetes Config Security)"
      inputs:
        targetType: 'inline'
        script: |
          set -e

          echo "Running Trivy config scan on Helm chart directory..."
          export PATH="$PWD/trivy-bin:$PATH"

          trivy config \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            $(Build.SourcesDirectory)/helm


# -----------------------
# Deploy Stage (Helm) - uses Environment SQA
# -----------------------
- stage: Deploy
  displayName: "Helm Deploy to AKS"
  dependsOn: Build

  jobs:
  - deployment: DeployToAKS                # <- deployment job
    displayName: "Deploy using Helm"

    environment:                            # <- Azure DevOps Environment
      name: 'SQA'                           # Environment name
      resourceName: 'karthi'                # Kubernetes resource under SQA
      resourceType: 'Kubernetes'

    pool:
      name: "Default"
      demands:
        - agent.name -equals Terraform

    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              git config --global --unset-all http.extraheader || true
              git config --local --unset-all http.extraheader || true
            displayName: "Reset leftover Git extraheader"

          - checkout: self
            clean: true
            persistCredentials: true

          - task: AzureCLI@2
            displayName: "Deploy Helm Chart to AKS (with Canary Support)"
            inputs:
              azureSubscription: "$(azureSubscription)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Getting AKS credentials..."
                az aks get-credentials \
                  --resource-group $(aksResourceGroup) \
                  --name $(aksCluster) \
                  --overwrite-existing

                echo "Installing Helm..."
                curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

                echo "Moving into local Helm folder..."
                cd $(Build.SourcesDirectory)/helm

                echo "Deploying with Helm (Canary Enabled)..."
                helm upgrade --install karthickapp . \
                  --set image.repository=$(acrName).azurecr.io/$(imageName) \
                  --set image.tag=$(Build.BuildId) \
                  --set canary.enabled=true \
                  --set canary.tag=$(Build.BuildId) \
                  --set canary.weight=20 \
                  --set service.type=LoadBalancer \
                  --wait --timeout 5m
